# Generated by Django 2.2.4 on 2019-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition', models.DateTimeField(auto_now_add=True, verbose_name='Expedition')),
                ('sender_name', models.CharField(max_length=150, verbose_name='Sender Name')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Recipient Name')),
                ('sender_address', models.TextField(verbose_name='Sender')),
                ('recipient_address', models.TextField(verbose_name='Recipient')),
                ('postal_code', models.CharField(max_length=36, verbose_name='Postal Code')),
                ('shipment_code', models.CharField(max_length=36, verbose_name='Product Code')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['shipment_code', 'id'],
            },
        ),
    ]
